# Generated by Django 6.0.7 on 2026-07-19 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('properties_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land'), ('commercial', 'Commercial'), ('office', 'Office'), ('warehouse', 'Warehouse'), ('car', 'Car')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(max_length=255)),
                ('images', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
                ('posted_date', models.DateField()),
                ('for_sale', models.BooleanField(default=True)),
                ('for_rent', models.BooleanField(default=False)),
                ('rent_price', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.agent')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-posted_date', '-id'],
            },
        ),
    ]
