# Generated by Django 6.0.7 on 2026-07-19 23:59

import backend.app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['name'], 'verbose_name': 'agent', 'verbose_name_plural': 'agents'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-posted_date', '-id'], 'verbose_name': 'property listing', 'verbose_name_plural': 'property listings'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['id'], 'verbose_name': 'testimonial', 'verbose_name_plural': 'testimonials'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.AlterField(
            model_name='agent',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Short bio'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, help_text='Click Choose file to upload a photo.', upload_to=backend.app.models.agent_image_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='properties_count',
            field=models.PositiveIntegerField(default=0, help_text='Optional display number. Active listings are counted automatically in admin.', verbose_name='Listed count (manual)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Full article body.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(verbose_name='Publish date'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(help_text='Short preview shown in lists.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Click Choose file to upload a cover image.', upload_to=backend.app.models.blog_image_path, verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.agent', verbose_name='Assigned agent'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.PositiveIntegerField(default=0, help_text='Square meters for property, or leave 0 for cars.', verbose_name='Size / area'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(help_text='Full listing description for the detail page.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show this listing in the Featured section on the homepage.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of labels, e.g. ["Swimming pool", "24hr security"]', verbose_name='Amenities / features'),
        ),
        migrations.AlterField(
            model_name='property',
            name='for_rent',
            field=models.BooleanField(default=False, verbose_name='Available for rent'),
        ),
        migrations.AlterField(
            model_name='property',
            name='for_sale',
            field=models.BooleanField(default=True, verbose_name='Available for sale'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, help_text='Click Choose file to upload the main listing photo.', upload_to=backend.app.models.property_image_path, verbose_name='Main photo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(help_text='Neighborhood or area, e.g. East Legon', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='posted_date',
            field=models.DateField(verbose_name='Date posted'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(help_text='Whole number in Ghana Cedis, no commas.', verbose_name='Sale price (GHS)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_price',
            field=models.PositiveIntegerField(blank=True, help_text='Required if “Available for rent” is checked.', null=True, verbose_name='Monthly rent (GHS)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(help_text='Headline shown on cards and detail pages.', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land'), ('commercial', 'Commercial'), ('office', 'Office'), ('warehouse', 'Warehouse'), ('car', 'Car')], max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(verbose_name='Quote'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Click Choose file to upload a photo.', upload_to=backend.app.models.testimonial_image_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Client name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='1–5 stars'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(help_text='e.g. Home buyer · Accra', max_length=120),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=backend.app.models.property_gallery_path, verbose_name='Photo')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='listings.property')),
            ],
            options={
                'verbose_name': 'gallery photo',
                'verbose_name_plural': 'gallery photos',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
